name: Node.js CI

on:   
  push:
    branches:
      - lagagain
  # Also trigger on page_build, as well as release created events
  page_build:
  release:
    types: # This configuration does not affect the page_build event above
      - created
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x,]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present\
      env:
        CI: true
        
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.2.5
      with:
          # Build directory to deploy
          build_dir:  ./dist
          keep_history: true
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
